name: First Workflow
# when will this workfflow be executed ? IOW: what event will trigger this workflow ?
#  the next workflow can be triggered manually
on: workflow_dispatch 
# then we define jobs
# identetion is key here
jobs:
  # here we declare the job name
  first-job:
    # here we declare the runner (where it will be executed) with the steps to me executed
    runs-on: ubuntu-latest
    # now we declare what steps to execute
    # those are defined with dashed key-value pairs
    steps:
      # first the name of the step
      - name: Print greeting
        # command to be executed
        run: echo "Hi there!"
      - name: Print bye
        run: echo "Bye bye !"
